name: occam
description: Minimalist state managment
version: 1.0.6
homepage: https://github.com/unacorbatanegra/occam

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  
dev_dependencies:
  mockito: ^5.4.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.4.6
  test_cov_console: ^0.2.2
  
  
flutter:
  uses-material-design: true
 